### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by SafeCodee** [39parrot/gravity#1]
After running jasmine-node flight.spec.js

Full message:
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

Now we use process.setMaxListeners(0) to don't show this warning

**Comment by piton182** [comment]
Ok, can we do it not in the file of spec?

**Comment by SafeCodee** [comment]
Moved to https://github.com/39parrot/turbulence/issues/15
